const Joi = require('joi');

const createEmployeeSchema = Joi.object({
  first_name: Joi.string().required(),
  last_name: Joi.string().required(),
  email: Joi.string().email().required(),
  phone: Joi.string().optional().allow(''),
  department: Joi.string().optional().allow(''),
  position: Joi.string().optional().allow(''),
  job_title: Joi.string().optional().allow(''),
  status: Joi.string().valid('active', 'on_leave', 'remote', 'inactive').default('active'),
  hire_date: Joi.date().optional(),
  salary: Joi.number().optional(),
  employee_id: Joi.string().optional().allow(''),
  manager_id: Joi.string().uuid().optional().allow(null),
  address: Joi.string().optional().allow(''),
  cnic: Joi.string().optional().allow(''),
  cnic_picture: Joi.string().optional().allow(''),
  profile_picture: Joi.string().optional().allow(''),
  date_of_birth: Joi.date().optional(),
  secondary_phone: Joi.string().optional().allow(''),
  official_email: Joi.string().email().optional().allow(''),
  personal_email: Joi.string().email().optional().allow(''),
  religion: Joi.string().optional().allow(''),
  probation_status: Joi.string().valid('on_probation', 'completed', 'extended').optional(),
  probation_end_date: Joi.date().optional(),
  commission_rate: Joi.number().min(0).max(100).optional(),
  base_salary: Joi.number().optional(),
  emergency_contact_name: Joi.string().optional().allow(''),
  emergency_contact_phone: Joi.string().optional().allow(''),
  emergency_contact_relation: Joi.string().optional().allow(''),
  blood_group: Joi.string().optional().allow(''),
  marital_status: Joi.string().optional().allow(''),
  gender: Joi.string().optional().allow(''),
  nationality: Joi.string().optional().allow(''),
  permanent_address: Joi.string().optional().allow(''),
  current_address: Joi.string().optional().allow(''),
  city: Joi.string().optional().allow(''),
  state: Joi.string().optional().allow(''),
  postal_code: Joi.string().optional().allow(''),
  country: Joi.string().optional().allow(''),
  bank_name: Joi.string().optional().allow(''),
  bank_account_number: Joi.string().optional().allow(''),
  bank_account_title: Joi.string().optional().allow(''),
  tax_id: Joi.string().optional().allow(''),
  education_level: Joi.string().optional().allow(''),
  university: Joi.string().optional().allow(''),
  degree: Joi.string().optional().allow(''),
  graduation_year: Joi.number().optional(),
  previous_company: Joi.string().optional().allow(''),
  previous_position: Joi.string().optional().allow(''),
  years_of_experience: Joi.number().optional(),
  skills: Joi.array().items(Joi.string()).optional(),
  certifications: Joi.array().items(Joi.string()).optional(),
  languages: Joi.array().items(Joi.string()).optional(),
  notes: Joi.string().optional().allow(''),
});

const updateEmployeeSchema = Joi.object({
  first_name: Joi.string().optional(),
  last_name: Joi.string().optional(),
  email: Joi.string().email().optional(),
  phone: Joi.string().optional().allow(''),
  department: Joi.string().optional().allow(''),
  position: Joi.string().optional().allow(''),
  job_title: Joi.string().optional().allow(''),
  status: Joi.string().valid('active', 'on_leave', 'remote', 'inactive').optional(),
  hire_date: Joi.date().optional(),
  salary: Joi.number().optional(),
  employee_id: Joi.string().optional().allow(''),
  manager_id: Joi.string().uuid().optional().allow(null),
  address: Joi.string().optional().allow(''),
  cnic: Joi.string().optional().allow(''),
  cnic_picture: Joi.string().optional().allow(''),
  profile_picture: Joi.string().optional().allow(''),
  date_of_birth: Joi.date().optional(),
  secondary_phone: Joi.string().optional().allow(''),
  official_email: Joi.string().email().optional().allow(''),
  personal_email: Joi.string().email().optional().allow(''),
  religion: Joi.string().optional().allow(''),
  probation_status: Joi.string().valid('on_probation', 'completed', 'extended').optional(),
  probation_end_date: Joi.date().optional(),
  commission_rate: Joi.number().min(0).max(100).optional(),
  base_salary: Joi.number().optional(),
  emergency_contact_name: Joi.string().optional().allow(''),
  emergency_contact_phone: Joi.string().optional().allow(''),
  emergency_contact_relation: Joi.string().optional().allow(''),
  blood_group: Joi.string().optional().allow(''),
  marital_status: Joi.string().optional().allow(''),
  gender: Joi.string().optional().allow(''),
  nationality: Joi.string().optional().allow(''),
  permanent_address: Joi.string().optional().allow(''),
  current_address: Joi.string().optional().allow(''),
  city: Joi.string().optional().allow(''),
  state: Joi.string().optional().allow(''),
  postal_code: Joi.string().optional().allow(''),
  country: Joi.string().optional().allow(''),
  bank_name: Joi.string().optional().allow(''),
  bank_account_number: Joi.string().optional().allow(''),
  bank_account_title: Joi.string().optional().allow(''),
  tax_id: Joi.string().optional().allow(''),
  education_level: Joi.string().optional().allow(''),
  university: Joi.string().optional().allow(''),
  degree: Joi.string().optional().allow(''),
  graduation_year: Joi.number().optional(),
  previous_company: Joi.string().optional().allow(''),
  previous_position: Joi.string().optional().allow(''),
  years_of_experience: Joi.number().optional(),
  skills: Joi.array().items(Joi.string()).optional(),
  certifications: Joi.array().items(Joi.string()).optional(),
  languages: Joi.array().items(Joi.string()).optional(),
  notes: Joi.string().optional().allow(''),
});

module.exports = {
  createEmployeeSchema,
  updateEmployeeSchema,
};
