-- Add complex fields to contacts table to support signing parties and detailed contacts
ALTER TABLE public.contacts
ADD COLUMN IF NOT EXISTS second_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS salutation VARCHAR(50),
ADD COLUMN IF NOT EXISTS dob DATE,
ADD COLUMN IF NOT EXISTS photo_url TEXT,
ADD COLUMN IF NOT EXISTS website VARCHAR(255),
ADD COLUMN IF NOT EXISTS website_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS messenger VARCHAR(255),
ADD COLUMN IF NOT EXISTS messenger_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS source VARCHAR(100),
ADD COLUMN IF NOT EXISTS source_info TEXT,
ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS include_in_export BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS responsible_id UUID REFERENCES public.users(id),
ADD COLUMN IF NOT EXISTS observers UUID[];
