-- =====================================================
-- Migration: Complete CRM Columns Fix
-- Description: Adds all missing columns to CRM tables
-- Date: 2026-04-02
-- =====================================================

-- ==================== CONTACTS TABLE ====================
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS company_id UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS second_name VARCHAR(255);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS salutation VARCHAR(50);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS position VARCHAR(255);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS website_type VARCHAR(50);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS messenger VARCHAR(255);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS messenger_type VARCHAR(50);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS contact_type VARCHAR(50) DEFAULT 'contact';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS source VARCHAR(100);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS source_info TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT true;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS include_in_export BOOLEAN DEFAULT true;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS available_to_everyone BOOLEAN DEFAULT true;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS included_in_export BOOLEAN DEFAULT true;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS responsible_id UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS observers UUID[];
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS company VARCHAR(255);

-- ==================== COMPANIES TABLE ====================
ALTER TABLE companies ADD COLUMN IF NOT EXISTS revenue NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS created_by UUID;

-- ==================== LEADS TABLE ====================
ALTER TABLE leads ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS workspace_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS contact_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS external_source_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS external_id VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS stage VARCHAR(100) DEFAULT 'new';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS value NUMERIC DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'USD';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_email VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_phone VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS designation VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_size VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS decision_maker VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS service_interested VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS interaction_notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS first_message TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_touch TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source_info JSONB;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS website_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS customer_type VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_contacted_date TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_follow_up_date TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS responsible_person VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS priority VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE leads ADD COLUMN IF NOT EXISTS expected_close_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS import_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_by UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_to_deal_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS is_converted BOOLEAN DEFAULT false;

-- ==================== DEALS TABLE ====================
ALTER TABLE deals ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS workspace_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS priority VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS source VARCHAR(100);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS designation VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS company_phone VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS company_email VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS company_size VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS decision_maker VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS service_interested VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS interaction_notes TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS first_message TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS last_touch TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS source_info JSONB;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS phone_type VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS email_type VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS website_type VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS customer_type VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS last_contacted_date TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS next_follow_up_date TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS responsible_person VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS linked_company_name VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS linked_company_phone VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS linked_company_email VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_first_name VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_last_name VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS tags TEXT[];

-- ==================== CRM_ACTIVITIES TABLE ====================
CREATE TABLE IF NOT EXISTS crm_activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  user_id UUID,
  entity_type VARCHAR(50),
  entity_id UUID,
  activity_type VARCHAR(100),
  title VARCHAR(255),
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==================== DEAL_CONTACTS TABLE ====================
CREATE TABLE IF NOT EXISTS deal_contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  deal_id UUID NOT NULL,
  contact_id UUID NOT NULL,
  role VARCHAR(100),
  primary_contact BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(org_id, deal_id, contact_id)
);

-- =====================================================
-- End of Migration
-- =====================================================
